-- data.sql
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Queen', 'Bohemian Rhapsody');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'The Beatles', 'Let It Be');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Michael Jackson', 'Billie Jean');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Eminem', 'Lose Yourself');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Nirvana', 'Smells Like Teen Spirit');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'AC/DC', 'Back In Black');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Metallica', 'Enter Sandman');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Linkin Park', 'In the End');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Coldplay', 'Fix You');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Adele', 'Rolling In The Deep');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Ed Sheeran', 'Shape of You');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'The Weeknd', 'Blinding Lights');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Drake', 'God''s Plan');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Imagine Dragons', 'Believer');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Billie Eilish', 'Bad Guy');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Dua Lipa', 'Levitating');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Daft Punk', 'Get Lucky');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Post Malone', 'Circles');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Rihanna', 'Diamonds');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Sia', 'Chandelier');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'U2', 'With or Without You');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Bon Jovi', 'It''s My Life');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Oasis', 'Wonderwall');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Radiohead', 'Creep');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'The Rolling Stones', 'Paint It Black');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Elton John', 'Rocket Man');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Whitney Houston', 'I Will Always Love You');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Red Hot Chili Peppers', 'Californication');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Foo Fighters', 'Everlong');
insert into song (id, artist, name) values (nextval('song_id_seq'), 'Kanye West', 'Stronger');
